### ISSUE TITLE
:modern doesn't make much sense in defreadtable

### ISSUE THREAD

**Issue by ailisp** [melisgl/named-readtables#12]
When defining a readtable with `(:merge :modern)` without `(:case :preserve)`, it still a "upcase" readtable:
```
ILLUSION> (defreadtable illusion-readtable
                      (:merge :modern))
{10027E0273}>.
#<NAMED-READTABLE ILLUSION-READTABLE {10027E0273}>
ILLUSION> *readtable*
#<NAMED-READTABLE ILLUSION-READTABLE {10027E0273}>
ILLUSION> (readtable-case *readtable*)
:UPCASE
```

**Comment by melisgl** [comment]
:MERGE and MERGE-READTABLES-INTO merge macro chars only and signal an error on conflict.
It's unclear what the right semantics for merging CASE would be.
Updated the documentation in 08c0df90d747220414eda3e0888fefeed2e40f0f to reflect this state of affairs.

**Comment by ailisp** [comment]
Thanks! New document looks very clear. I was assume MODERN means a case preserve read table.
