### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [melisgl/named-readtables#3]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by phoe** [comment]
That's already done:

https://github.com/melisgl/named-readtables/blob/78f987ac46f09a087b0a1ffc24078e2984864eee/named-readtables.asd#L14-L20

**Comment by melisgl** [comment]
Added even more in d4b10eeefedb330fce7df1c16872df49641fb66b.
