### ISSUE TITLE
Error loading named-readtables with MKCL

### ISSUE THREAD

**Issue by m-e-leypold** [melisgl/named-readtables#30]
Just the following (in the SLIME REPL)

```
CL-USER> (asdf:load-system "named-readtables")
;;; Warning: in file /user/home/mel/my/quicklisp/dists/quicklisp/software/named-readtables-20220331-git/src/named-readtables.lisp, end position 14949,
;;;     and form: (DEFINE-API MERGE-READTABLES-INTO (RESULT-READTABLE &REST NAMED-READTABLES) ...)
;;;   Too many arguments passed to SET-MACRO-CHARACTER
```
and then in a slime backtrace buffer:

```
COMPILE-FILE-ERROR while compiling
   #<ASDF/INTERFACE::NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables">
   [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]

Restarts:
 0: [RETRY] Retry compiling #<ASDF/INTERFACE::NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables">.
 1: [ACCEPT] Continue, treating compiling #<ASDF/INTERFACE::NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables"> as having been successful.
 2: [RETRY] Retry ASDF operation.
 3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 4: [RETRY] Retry ASDF operation.
 5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 --more--

Backtrace:
  0: LAMBDA, closure generated from SWANK-DEBUGGER-HOOK
  1: BYTECODE [Evaluation of: (ASDF/OPERATE:LOAD-SYSTEM "named-readtables")]
  2: LAMBDA, closure generated from LAMBDA
  3: TRACK-PACKAGE
  4: LAMBDA, closure generated from LAMBDA
  5: LAMBDA, closure generated from REPL-EVAL
```

I am a bit lost what the problem is, since also I seem to be able to load the referenced file just fine:

```
CL-USER> (load "/user/home/mel/my/quicklisp/dists/quicklisp/software/named-readtables-20220331-git/src/named-readtables.lisp")
#P"/user/home/mel/my/quicklisp/dists/quicklisp/software/named-readtables-20220331-git/src/named-readtables.lisp"
CL-USER> 
```
The two occurrences of SET-MACRO-CHARACTER in the file also look totally fine and have 4 arguments which should be fine according to the CLHS.

Admittedly this issue is a bit of a fishing expedition. I'm a bit lost how to debug this on the MKCL side (the backtrace does not contain useful information and as opposed to what I get with SBCL it does not point back to the MKCL implementation source).
 I'll create a MKCL issue as well, but hope that there is some know-how available here, how to get named-readtables working on mkcl.

The MKCL version I'm using:

```
$ mkcl --version
MKCL 1.1.11.187-19222c1
````

If I start with an empty compilation cache I get some additional warnings, which as precursors might be of interest. I'll document those in an extra reply-.

Side note: name-readtables loads fine for me on: sbcl ecl clasp ccl cmucl clisp abcl.

**Comment by m-e-leypold** [comment]
Starting with an empty compilation cache:

```
CL-USER> (asdf:load-system "named-readtables")
;;; Warning: 
  EDITOR-HINTS.NAMED-READTABLES has not been ported to MKCL. We fall back to a
  portable implementation of readtable iterators. This implementation has to
  grovel through all available characters. On Unicode-aware implementations
  this may come with some costs.
;;; Warning: Lisp compilation had style-warnings while compiling
   #<ASDF/INTERFACE::NAMED-READTABLES-SOURCE-FILE "named-readtables" "cruft">
;;; Warning: in file /user/home/mel/my/quicklisp/dists/quicklisp/software/named-readtables-20220331-git/src/named-readtables.lisp, end position 14949,
;;;     and form: (DEFINE-API MERGE-READTABLES-INTO (RESULT-READTABLE &REST NAMED-READTABLES) ...)
;;;   Too many arguments passed to SET-MACRO-CHARACTER
```

**Comment by melisgl** [comment]
I have no idea what's happening. I tried to reproduce but couldn't even `(require "asdf")` on a freshly compiled MKCL on Linux.

**Comment by m-e-leypold** [comment]
It seems it was a bug in MKCL. Not sure what I did that asdf works for me -- there is possibly a copy of asdf in quicklisp, and of course in my mkclrc I set up quicklisp.

Could you wait with closing this issue, until I have verified that it was indeed an MKCL problem? I'll link to the issue over there then.

**Comment by m-e-leypold** [comment]
OK, it was, indeed, an error in MKCL => https://github.com/jcbeaudoin/MKCL/issues/13.

But thank you very much regardless!

**Comment by m-e-leypold** [comment]
Regarding that require: I think it must be (at least in the case of MKCL):
```
(require 'asdf)
```
AFAIR (now ...) quicklisp does exactly this to activate the actually built-in ASDF.
