### ISSUE TITLE
`WITHOUT-PACKAGE-LOCK` does not work under LispWorks 7.0

### ISSUE THREAD

**Issue by tuscland** [melisgl/named-readtables#4]
Hello,

The macro `WITHOUT-PACKAGE-LOCK` does not work under LW 7.0.
The reason is that LW now uses the designator `:implementation` for all implementation dependent packages which makes it impossible to perform set difference of package names.

I don't see how it would be possible to keep the same functionality, but to prevent package redefinition error behavior for any package.

Best,
Cam

**Comment by melisgl** [comment]
WITHOUT-PACKAGE-LOCK is not exported. Are you getting an error loading named-readtables?

**Comment by melisgl** [comment]
I'm not sure what the issue here is. Closing.
