### ISSUE TITLE
Is CMUCL supported?

### ISSUE THREAD

**Issue by binghe** [melisgl/named-readtables#9]
Hi there,

Is CMUCL supported for named-readtables?  Currently I can't compile named-readtables in CMUCL (21a), the problematic definition is this one:

(define-api make-readtable
    (&optional (name nil name-supplied-p) &key merge)
    (&optional named-readtable-designator &key (:merge list) => readtable)
 . .. )

If I load this form manually, then I got the following compiler errors:

Error in function LISP::ASSERT-ERROR:
   The assertion (OR (NULL OPTS) (EQ (POP TYPE-LIST) '&OPTIONAL)) failed.
   [Condition of type SIMPLE-ERROR]

Regards,

Chun Tian (binghe)

**Comment by cbaggers** [comment]
Just adding a bump to this issue. Would like to know the same

**Comment by melisgl** [comment]
Merged the above fix, but the tests are still broken. I guess, the answer is not.

**Comment by rtoy** [comment]
Actually, see #22.  Cmucl is supported.

**Comment by binghe** [comment]
> Actually, see #22. Cmucl is supported.

Good to know, thanks.
